# Auto-generated by repobuild, do not modify directly.

# Environment flag settings.
ROOT_DIR := $(shell pwd)
# Some compiler specific flag settings.
CXX_GCC := $(shell echo $$($(CXX) --version | egrep '(gcc|g\+\+)' | head -n 1 | wc -l))
CC_GCC := $(shell echo $$($(CC) --version | egrep '(gcc|g\+\+|^cc)' | head -n 1 | wc -l))
ifeq ($(CC_GCC),1)
	CFLAGS= -pthread -g -Wall -Werror -Wno-sign-compare -Wno-unused-local-typedefs -Wno-error=unused-local-typedefs -O3 -flto
	BASIC_CFLAGS= -pthread
else
	CFLAGS= -stdlib=libc++ -pthread -g -Wall -Werror -Wno-sign-compare -O3 -flto -Qunused-arguments -fcolor-diagnostics
	BASIC_CFLAGS= -stdlib=libc++ -pthread -Qunused-arguments
endif
ifeq ($(CXX_GCC),1)
	LD_FORCE_LINK_START := -Wl,--whole-archive
	LD_FORCE_LINK_END := -Wl,--no-whole-archive
	LDFLAGS= -lpthread -g -O3 -flto -L/usr/local/lib -L/opt/local/lib
	CXXFLAGS= -pthread -g -Wall -Werror -Wno-sign-compare -Wno-unused-local-typedefs -Wno-error=unused-local-typedefs -O3 -flto -std=c++11 -DUSE_CXX0X
	BASIC_CXXFLAGS= -pthread -std=c++11
else
	LD_FORCE_LINK_START := -Wl,-force_load
	LD_FORCE_LINK_END := 
	LDFLAGS= -stdlib=libc++ -lpthread -g -O3 -flto -L/usr/local/lib -L/opt/local/lib
	CXXFLAGS= -stdlib=libc++ -pthread -g -Wall -Werror -Wno-sign-compare -O3 -flto -Qunused-arguments -fcolor-diagnostics -std=c++11 -DUSE_CXX0X
	BASIC_CXXFLAGS= -stdlib=libc++ -pthread -Qunused-arguments -std=c++11
endif

# Some platform specific flag settings.
IS_DARWIN := $(shell echo $$(uname | grep 'Darwin' | wc -l))
IS_DARWIN_AND_CLANG := $(shell echo $$((($(IS_DARWIN) == 1 && $(CXX_GCC) == 0))))
ifeq ($(IS_DARWIN_AND_CLANG),1)
	SHARED_LIB_ARGS_R:=awk '{print "-dynamiclib -current_version "$$3" -compatibility_version "$$4}'
	SHARED_LIB_ARGS_MI:=awk '{print "-dynamiclib -current_version "$$3}'
	SHARED_LIB_ARGS_MA:=awk '{print "-dynamiclib"}'
	SHARED_LIB_ARGS:=awk '{print "-dynamiclib"}'
	SHARED_LIB_NAME_R:=awk '{print "lib"$$1"."$$2"."$$3"."$$4".dylib"}'
	SHARED_LIB_NAME_MI:=awk '{print "lib"$$1"."$$2"."$$3".dylib"}'
	SHARED_LIB_NAME_MA:=awk '{print "lib"$$1"."$$2".dylib"}'
	SHARED_LIB_NAME:=awk '{print "lib"$$1".dylib"}'
else
	SHARED_LIB_ARGS_R:=awk '{print "-shared -Wl,-soname,lib"$$1".so."$$2}'
	SHARED_LIB_ARGS_MI:=awk '{print "-shared -Wl,-soname,lib"$$1".so."$$2}'
	SHARED_LIB_ARGS_MA:=awk '{print "-shared -Wl,-soname,lib"$$1".so."$$2}'
	SHARED_LIB_ARGS:=awk '{print "-shared -Wl,-soname,lib"$$1".so"}'
	SHARED_LIB_NAME_R:=awk '{print "lib"$$1".so."$$2"."$$3"."$$4}'
	SHARED_LIB_NAME_MI:=awk '{print "lib"$$1".so."$$2"."$$3}'
	SHARED_LIB_NAME_MA:=awk '{print "lib"$$1".so."$$2}'
	SHARED_LIB_NAME:=awk '{print "lib"$$1".so"}'
endif
define PythonSetup
aW1wb3J0IG9zCmZyb20gc2V0dXB0b29scyBpbXBvcnQgc2V0dXAKCnNldHVwKAogICAgbmFtZSA9IG9zLmVudmlyb25bJ1BZX05BTUUnXSwKICAgIHZlcnNpb24gPSBvcy5lbnZpcm9uWydQWV9WRVJTSU9OJ10sCiAgICBweV9tb2R1bGVzID0gb3MuZW52aXJvblsnUFlfTU9EVUxFUyddLnNwbGl0KCksCiAgICBpbnN0YWxsX3JlcXVpcmVzID0gb3MuZW52aXJvblsnUFlfU1lTX0RFUFMnXS5zcGxpdCgpLAopCg==
endef
export PythonSetup

.gen-pkg/base_setup.py: 
	@mkdir -p .gen-pkg
	@echo "$$PythonSetup" | base64 --decode > .gen-pkg/base_setup.py
	@chmod 0755 .gen-pkg/base_setup.py

define CCEmbed
IyEvYmluL2Jhc2gKSEVBREVSPSIkMSIKQ1BQPSIkMiIKR1VBUkQ9IiQzIgpOQU1FU1BBQ0VfU1RBUlQ9IiQ0IgpOQU1FU1BBQ0VfRU5EPSIkNSIKZWNobyAiI2lmbmRlZiAkR1VBUkQiID4gJEhFQURFUgplY2hvICIjZGVmaW5lICRHVUFSRCIgPj4gJEhFQURFUgplY2hvICIjaW5jbHVkZSA8Y3N0cmluZz4gIC8vIHNpemVfdCIgPj4gJEhFQURFUgplY2hvICIkTkFNRVNQQUNFX1NUQVJUIiA+PiAkSEVBREVSCmVjaG8gIiNpbmNsdWRlIFwiJChiYXNlbmFtZSAkSEVBREVSKVwiIiA+ICRDUFAKZWNobyAiJE5BTUVTUEFDRV9TVEFSVCIgPj4gJENQUAp3aGlsZSByZWFkIFNPVVJDRSBWQVJJQUJMRTsgZG8gIGVjaG8gIi8vIEF1dG8gZ2VuZXJhdGVkIGZyb20gJFNPVVJDRSIgPj4gJEhFQURFUgogIGVjaG8gImV4dGVybiBjb25zdCBjaGFyKiAiJFZBUklBQkxFIl9kYXRhKCk7IiA+PiAkSEVBREVSCiAgZWNobyAiZXh0ZXJuIHNpemVfdCAiJFZBUklBQkxFIl9zaXplKCk7IiA+PiAkSEVBREVSCiAgZWNobyAiIiA+PiAkSEVBREVSCiAgZWNobyAiY29uc3QgY2hhciogIiRWQVJJQUJMRSJfZGF0YSgpIHsiID4+ICRDUFAKICBwcmludGYgIiAgcmV0dXJuIFwiIiA+PiAkQ1BQCiAgY2F0ICRTT1VSQ0UgICAgIHwgcGVybCAtcGUgJ3N8XFx8XFxcXHxnJyAgICAgfCBwZXJsIC1wZSAnc3xcInxcXCJ8ZycgICAgIHwgcGVybCAtcGUgJ3N8XG58XFxufGcnID4+ICRDUFAKICBlY2hvICJcIjsiID4+ICRDUFAKICBlY2hvICJ9IiA+PiAkQ1BQCiAgZWNobyAic2l6ZV90ICIkVkFSSUFCTEUiX3NpemUoKSIgeyA+PiAkQ1BQCiAgcHJpbnRmICIgIHJldHVybiAiID4+ICRDUFAKICBwcmludGYgJChjYXQgJFNPVVJDRSB8IHdjIC1jKSA+PiAkQ1BQCiAgZWNobyAiOyIgPj4gJENQUAogIGVjaG8gIn0iID4+ICRDUFAKZG9uZQplY2hvICIkTkFNRVNQQUNFX0VORCIgPj4gJEhFQURFUgplY2hvICIjZW5kaWYgIC8vICRHVUFSRCIgPj4gJEhFQURFUgplY2hvICIkTkFNRVNQQUNFX0VORCIgPj4gJENQUAo=
endef
export CCEmbed

.gen-files/cc_embed.sh: 
	@mkdir -p .gen-files
	@echo "$$CCEmbed" | base64 --decode > .gen-files/cc_embed.sh
	@chmod 0755 .gen-files/cc_embed.sh

define FlockScript
IyEvdXNyL2Jpbi9wZXJsIAojIGJhc2ljYWxseSBmbG9jaywgbW9kaWZpZWQgZnJvbSBzb3VyY2Ugb24gdGhlIHdlYi4KCnVzZSB3YXJuaW5nczsKdXNlIHN0cmljdDsKdXNlIEZjbnRsIHF3KDpmbG9jayk7CgpteSAkbG9ja2ZpbGUgPSBzaGlmdDsKbXkgJGNvbW1hbmQgPSBqb2luKCIgIixAQVJHVik7CgppZiAoISRsb2NrZmlsZSB8fCAhJGNvbW1hbmQpIHsKICAgIGRpZSgidXNhZ2U6ICQwIDxmaWxlPiA8Y29tbWFuZD5cbiIpOwp9CgpvcGVuKEZILCRsb2NrZmlsZSkgfHwgZGllKCQhKTsgCmZsb2NrKEZILExPQ0tfRVgpIHx8IGRpZSgkISk7Cm15ICRyZXR2YWwgPSAwOwpzeXN0ZW0oJGNvbW1hbmQpID09IDAgb3IgJHJldHZhbCA9ICQ/ID4+IDg7CmZsb2NrKEZILExPQ0tfVU4pOyAKZXhpdCgkcmV0dmFsKTsK
endef
export FlockScript

.gen-files/flock_script.pl: 
	@mkdir -p .gen-files
	@echo "$$FlockScript" | base64 --decode > .gen-files/flock_script.pl
	@chmod 0755 .gen-files/flock_script.pl


.gen-obj/.parsercompile.dummy: Parser.java .gen-files/.dummy.prereqs
	@mkdir -p .gen-obj/lib_parser
	@echo "Compiling:  parser (java)"
	@mkdir -p .gen-obj/lib_parser
	@javac -d .gen-obj/lib_parser -s .gen-files -g -cp  .:.gen-files:.gen-src:.gen-src/.gen-files:.:.gen-files:.gen-obj:.gen-obj/lib_parser:.gen-src Parser.java
	@mkdir -p .gen-obj
	@touch .gen-obj/.parsercompile.dummy


.gen-obj/lib_parser/Parser.class: .gen-obj/.parsercompile.dummy .gen-files/.dummy.prereqs
	@if [ ! -f .gen-obj/lib_parser/Parser.class ]; then echo "Class file not generated: .gen-obj/lib_parser/Parser.class, or it was generated in an unexpected location. Make sure java_root is specified correctly or the package name for the object is: Parser.class"; exit 1; fi
	@touch .gen-obj/lib_parser/Parser.class


.gen-obj/lib_parser/.dummy.touch: .gen-obj/lib_parser/Parser.class .gen-files/.dummy.prereqs
	@mkdir -p .gen-obj/lib_parser
	@touch .gen-obj/lib_parser/.dummy.touch

parser: .gen-obj/lib_parser/Parser.class

.PHONY: parser


checker: .gen-obj/checker .gen-files/.dummy.prereqs
	@ln -f -s .gen-obj/checker checker


bin/checker: .gen-obj/checker .gen-files/.dummy.prereqs
	@mkdir -p bin
	@ln -f -s ../.gen-obj/checker bin/checker


checker.jar: .gen-obj/checker.jar .gen-files/.dummy.prereqs
	@ln -f -s .gen-obj/checker.jar checker.jar


bin/checker.jar: .gen-obj/checker.jar .gen-files/.dummy.prereqs
	@mkdir -p bin
	@ln -f -s ../.gen-obj/checker.jar bin/checker.jar

checker.0:

.PHONY: checker.0


.gen-obj/.checkercompile.dummy: Parser.java .gen-obj/lib_parser/Parser.class Checker.java .gen-files/.dummy.prereqs
	@mkdir -p .gen-obj/lib_checker
	@echo "Compiling:  checker (java)"
	@mkdir -p .gen-obj/lib_checker
	@javac -d .gen-obj/lib_checker -s .gen-files -g -cp  .:.gen-files:.gen-src:.gen-src/.gen-files:.:.gen-files:.gen-obj:.gen-obj/lib_checker:.gen-obj/lib_parser:.gen-src Checker.java
	@mkdir -p .gen-obj
	@touch .gen-obj/.checkercompile.dummy


.gen-obj/lib_checker/Checker.class: .gen-obj/.checkercompile.dummy .gen-files/.dummy.prereqs
	@if [ ! -f .gen-obj/lib_checker/Checker.class ]; then echo "Class file not generated: .gen-obj/lib_checker/Checker.class, or it was generated in an unexpected location. Make sure java_root is specified correctly or the package name for the object is: Checker.class"; exit 1; fi
	@touch .gen-obj/lib_checker/Checker.class


.gen-obj/lib_checker/.dummy.touch: .gen-obj/lib_checker/Checker.class .gen-files/.dummy.prereqs
	@mkdir -p .gen-obj/lib_checker
	@touch .gen-obj/lib_checker/.dummy.touch


.gen-obj/.checker2E67656E2D6F626A2F6C69625F7061727365722F2E64756D6D792E746F756368.dummy: .gen-obj/lib_parser/.dummy.touch .gen-files/.dummy.prereqs
	@mkdir -p .gen-pkg/checker
	@FILES=$$(cd .gen-obj/lib_parser; find . -type f -o -type l); cd .gen-pkg/checker; for file in $$FILES; do mkdir -p $$(dirname $$file); RELATIVE=$$(FILE=$$(dirname $$file); while [ "$$FILE" != "." ];   do printf '../'; FILE=$$(dirname $$FILE); done);  ln -s -f $$RELATIVE../../.gen-obj/lib_parser/$$file $$file; done
	@mkdir -p .gen-obj
	@touch .gen-obj/.checker2E67656E2D6F626A2F6C69625F7061727365722F2E64756D6D792E746F756368.dummy


.gen-obj/.checker2E67656E2D6F626A2F6C69625F636865636B65722F2E64756D6D792E746F756368.dummy: .gen-obj/lib_checker/.dummy.touch .gen-files/.dummy.prereqs
	@mkdir -p .gen-pkg/checker
	@FILES=$$(cd .gen-obj/lib_checker; find . -type f -o -type l); cd .gen-pkg/checker; for file in $$FILES; do mkdir -p $$(dirname $$file); RELATIVE=$$(FILE=$$(dirname $$file); while [ "$$FILE" != "." ];   do printf '../'; FILE=$$(dirname $$FILE); done);  ln -s -f $$RELATIVE../../.gen-obj/lib_checker/$$file $$file; done
	@mkdir -p .gen-obj
	@touch .gen-obj/.checker2E67656E2D6F626A2F6C69625F636865636B65722F2E64756D6D792E746F756368.dummy


.gen-files/checker.manifest: .gen-files/.dummy.prereqs
	@mkdir -p .gen-files
	@eval 'rm -f .gen-files/checker.manifest; for line in "Main-class: Checker"; do echo "$$line" >> .gen-files/checker.manifest; done; touch .gen-files/checker.manifest'


.gen-obj/checker.jar: .gen-files/checker.manifest .gen-obj/.checker2E67656E2D6F626A2F6C69625F7061727365722F2E64756D6D792E746F756368.dummy .gen-obj/.checker2E67656E2D6F626A2F6C69625F636865636B65722F2E64756D6D792E746F756368.dummy .gen-files/.dummy.prereqs
	@echo "Jaring:     .gen-obj/checker.jar"
	@mkdir -p .gen-pkg/checker
	@cd .gen-pkg/checker ; jar cfm ../../.gen-obj/checker.jar ../../.gen-files/checker.manifest $$(find . -type f -o -type l)


.gen-obj/checker: .gen-obj/checker.jar .gen-files/.dummy.prereqs
	@echo 'java -jar $$(pwd)/$$(dirname $$0)/.gen-obj/checker.jar' > .gen-obj/checker; chmod 755 .gen-obj/checker


clean: .gen-files/.dummy.prereqs
	@[ -L checker ] && rm -f checker || true
	@[ -L bin/checker ] && rm -f bin/checker || true
	@[ -L checker.jar ] && rm -f checker.jar || true
	@[ -L bin/checker.jar ] && rm -f bin/checker.jar || true
	@rm -rf .gen-obj
	@rm -rf bin
	@rm -rf .gen-files
	@rm -rf .gen-src
	@rm -rf .gen-pkg

# http://www.gnu.org/prep/standards/standards.html
prefix=/usr/local
exec_prefix=$(prefix)
bindir=$(exec_prefix)/bin
includedir=$(prefix)/include
libdir=$(exec_prefix)/lib
INSTALL=install
INSTALL_PROGRAM=$(INSTALL)
INSTALL_DATA=$(INSTALL) -m 644


install: .gen-files/.dummy.prereqs


all: checker bin/checker checker.jar bin/checker.jar .gen-files/.dummy.prereqs


tests: .gen-files/.dummy.prereqs


licenses: 
	@echo "License information."
	@printf "//:checker =>\n\n"

.PHONY: clean all tests install licenses

.DEFAULT_GOAL=all


.gen-files/.dummy.prereqs: 
	@mkdir -p .gen-files
	@touch .gen-files/.dummy.prereqs


prereqs: .gen-files/.dummy.prereqs

.PHONY: prereqs

